#! /bin/bash

# default apache virtualhosts path
PHD_APACHE_VIRTUALHOSTS='/etc/apache2/phd-sites'
PHD_APACHE_CONFIG='/etc/apache2/apache2.conf'
PHD_APACHE_INCLUDE="Include $PHD_APACHE_VIRTUALHOSTS"
PUSHAND_INSTALL_DIR=~/tmp

# read .phdrc (for overrides)
if [[ -f ~/.phdrc ]]; then
	source ~/.phdrc
fi

if [[ ! -w "$PHD_APACHE_CONFIG" ]]; then
	echo "Don't have permission to edit $PHD_APACHE_CONFIG"
	exit
fi

if [[ -z "$( which git-receive-pack_original )" ]]; then
	echo "Installing PushAnd"
	mkdir -p $PUSHAND_INSTALL_DIR
	cd $PUSHAND_INSTALL_DIR
	git clone git://github.com/remi/pushand.git
	cd pushand
	sudo ./pushand_server_install
fi

if [[ ! -f "$PHD_APACHE_VIRTUALHOSTS" ]]; then
	echo "Creating virtualhosts directory"
	mkdir -p $PHD_APACHE_VIRTUALHOSTS
	chmod a+rw $PHD_APACHE_VIRTUALHOSTS
fi

if [[ -z "$( grep '$PHD_APACHE_INCLUDE' $PHD_APACHE_CONFIG )" ]]; then
	echo "Including virtualhosts in configuration"
	echo $PHD_APACHE_INCLUDE >> $PHD_APACHE_CONFIG
fi
